#------------------------------------------------------------------------------
# Makefile to make ATLAS rounding note
#------------------------------------------------------------------------------

BASENAME = atlas_rounding

all:
	make -f ../Makefile BASENAME=$(BASENAME)

clean:
	make -f ../Makefile clean
	
cleanall: clean
	-rm $(BASENAME).pdf
