#------------------------------------------------------------------------------
# Makefile to make atlas-latex documentation
#------------------------------------------------------------------------------

BASENAME = atlas_latex

all:
	make -f ../Makefile BASENAME=$(BASENAME)

clean:
	make -f ../Makefile clean
	
cleanall: clean
	-rm $(BASENAME).pdf
