#------------------------------------------------------------------------------
# Makefile to make atlas-document documentation
#------------------------------------------------------------------------------

BASENAME = atlas-document

all:
	make -f ../Makefile BASENAME=$(BASENAME)

clean:
	make -f ../Makefile clean
	
cleanall: clean
	-rm $(BASENAME).pdf
