#------------------------------------------------------------------------------
# Makefile to make atlas_tables documentation
#------------------------------------------------------------------------------

BASENAME = atlas_tables

all:
	make -f ../Makefile BASENAME=$(BASENAME)

clean:
	make -f ../Makefile clean
	
cleanall: clean
	-rm $(BASENAME).pdf
