#------------------------------------------------------------------------------
# Makefile to make atlas_bibtex documentation
#------------------------------------------------------------------------------

BASENAME = atlas_bibtex

all:
	make -f ../Makefile BASENAME=$(BASENAME)

clean:
	make -f ../Makefile clean
	
cleanall: clean
	-rm $(BASENAME).pdf
