#------------------------------------------------------------------------------
# Makefile to make atlas_paper documentation
#------------------------------------------------------------------------------

BASENAME = atlas_paper

all:
	make -f ../Makefile BASENAME=$(BASENAME)

clean:
	make -f ../Makefile clean
	
cleanall: clean
	-rm $(BASENAME).pdf
