#------------------------------------------------------------------------------
# Makefile to make atlas-paper documentation
#------------------------------------------------------------------------------

BASENAME = atlas-paper

all:
	make -f ../Makefile BASENAME=$(BASENAME)

clean:
	make -f ../Makefile clean
	
cleanall: clean
	-rm $(BASENAME).pdf
