#------------------------------------------------------------------------------
# Makefile to make atlas-bibtex documentation
#------------------------------------------------------------------------------

BASENAME = atlas-bibtex

all:
	make -f ../Makefile BASENAME=$(BASENAME)

clean:
	make -f ../Makefile clean
	
cleanall: clean
	-rm $(BASENAME).pdf
