#------------------------------------------------------------------------------
# Makefile to make atlas-physics documentation
#------------------------------------------------------------------------------

BASENAME = atlas-physics

all:
	make -f ../Makefile BASENAME=$(BASENAME)

clean:
	make -f ../Makefile clean
	
cleanall: clean
	-rm $(BASENAME).pdf
